In [ ]:
# a. Импортируйте библиотеку NumPy
import numpy as np

In [ ]:
# b. Создайте массив из 10 нулей
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# c. Создать массив из 10 единиц
y = np.ones(10)
print(y)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# d. Создать массив из 10 пятерок
z = np.array([5,5,5,5,5,5,5,5,5,5])
print(z)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
# e. Создать массив из целых чисел от 10 до 50
q = np.arange(10,51,1)
print(q)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# f. Создать массив из четных чисел от 10 до 50
t = np.arange(10,51,2)
print(t)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# g. Создать матрицу 3х3 с числами от 0 до 8

matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# h. Создать единичную матрицу 3x3
n = np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# i. Используйте NumPy для генерации случайного числа от 0 до 1
rndm = np.random.rand(2)
print(rndm)

[0.41313228 0.16627379]


In [ ]:
# j. Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
rndm = np.random.rand(25)
print(rndm)

[0.16643054 0.45925429 0.17011085 0.63031108 0.35986703 0.60633206
 0.85881703 0.70860713 0.27014831 0.70310785 0.9501963  0.77244665
 0.7296545  0.40643112 0.23180261 0.94721989 0.73863829 0.32612638
 0.10128311 0.00566977 0.94526721 0.44393401 0.9322126  0.74161574
 0.19087755]


In [ ]:
# k. Создайте следующую матрицу используя функции библиотеки NumPy

matrix = np.arange(0.01,1.01,0.01)
print(matrix)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


In [ ]:
# Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# l. Необходимо написать код который вернет следующую матрицу из стартовой
x = mat[2:5,1:5]
print(x)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# m. Написать код обращения к элементу который вернет значение  20 из стартовой матрицы задачи l
x = mat[3][4:]
print(x)

[20]


In [ ]:
# n. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
x = mat[0:3,1::5]
print(x)

[[ 2]
 [ 7]
 [12]]


In [ ]:
# o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
x = mat[4:,:]
print(x)

[[21 22 23 24 25]]


In [ ]:
# p.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
x = mat[3:,:]
print(x)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
 # q. Получить сумму всех значений в стартовой матрице mat
print(mat.sum())
print('--------------')
s = 0
for i in mat:
    s+= sum(i)
print(s)

325
--------------
325


In [ ]:
# r. Получить стандартное отклонение в стартовой матрице mat
x = np.std(mat)
print(x)

7.211102550927978


In [ ]:
#s. Получить сумму значений в колонках в стартовой матрице mat
x = np.sum(mat, axis=0)
print(x)

[55 60 65 70 75]
